Upgrade for mineunit cli runner

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,5 +1,5 @@
 name: Mineunit runner
-description: "Execute unit tests with mineunit & busted"
+description: "Execute unit tests with mineunit, busted & luacov"
 author: SX / S-S-X
 branding:
   icon: file-text
@@ -10,9 +10,6 @@ inputs:
     description: "Working directory for unit tests"
     required: true
     default: "."
-  luacov-exclude:
-    description: "Code coverage exclude patterns"
-    required: false
   badge-name:
     description: "Code coverage badge name"
     required: true
@@ -28,10 +25,6 @@ inputs:
   mineunit-version:
     description: "Mineunit version"
     required: false
-  mineunit-directory:
-    description: "Mineunit install directory relative to working-directory"
-    required: true
-    default: "spec/mineunit"
 
 outputs:
   # Generated or supplied badge properties
@@ -48,13 +41,17 @@ outputs:
     description: "Code coverage badge color waiting for issues/#1"
     value: ${{ steps.badge-wrapper-actions-issue-1.outputs.badge-color }}
 
-  # Busted test framework output
-  busted-stdout:
+  # Mineunit test framework output
+  mineunit-stdout:
     description: "Stdout produced during busted run"
-    value: ${{ steps.busted-run.outputs.busted-stdout }}
-  busted-spec-missing:
-    description: "Set to true if no spec files found"
-    value: ${{ steps.busted-run.outputs.busted-spec-missing }}
+    value: ${{ steps.mineunit-tests.outputs.stdout }}
+  mineunit-spec-missing:
+    description: "Set to true if no spec files found for busted"
+    value: ${{ steps.mineunit-tests.outputs.spec-missing }}
+
+  mineunit-report:
+    description: "Mineunit detailed test report"
+    value: ${{ steps.mineunit-report.outputs.report }}
 
   # Help content / on demand documentation
   help-busted-spec-missing:
@@ -84,32 +81,31 @@ runs:
       shell: bash
       run: |
         luarocks install --server=https://luarocks.org/dev  --local mineunit ${{ inputs.mineunit-version }}
-    - name: luacov configuration
-      working-directory: "${{ inputs.working-directory }}"
-      shell: bash
-      run: |
-        excludes='${{ inputs.luacov-exclude && format('"{0}"',join(fromJSON(inputs.luacov-exclude),'","')) || '' }}'
-        echo 'deletestats=true;includeuntestedfiles=true;exclude={"spec/","/\.?luarocks/","/share/lua/",'"${excludes}"'}'>.luacov
-    - id: busted-run
-      name: busted run
+    - id: mineunit-tests
+      name: mineunit runner
       working-directory: "${{ inputs.working-directory }}"
       shell: bash
       run: |
         set +eo pipefail
         exec 3>&1
-        OUT="$($HOME/.luarocks/bin/busted -c | tee >(cat - >&3); exit ${PIPESTATUS[0]})"
+        OUT="$($HOME/.luarocks/bin/mineunit -c | tee >(cat - >&3); exit ${PIPESTATUS[0]})"
         ERR=$?
         exec 3>&-
         grep_eronly=(grep '0 successes / 0 failures / [1-9] error.\? / 0 pending')
         grep_nospec=(grep 'No test files found')
-        ("${grep_eronly[@]}"<<<"$OUT" && "${grep_nospec[@]}"<<<"$OUT")&>/dev/null && echo "::set-output name=busted-spec-missing::true"
+        ("${grep_eronly[@]}"<<<"$OUT" && "${grep_nospec[@]}"<<<"$OUT")&>/dev/null && echo "::set-output name=spec-missing::true"
         OUT="${OUT//'%'/'%25'}";OUT="${OUT//$'\n'/'%0A'}"
-        echo "::set-output name=busted-stdout::${OUT//$'\r'/'%0D'}"
+        echo "::set-output name=stdout::${OUT//$'\r'/'%0D'}"
         exit $ERR
-    - name: luacov run
+    - id: mineunit-report
+      name: mineunit coverage report
       working-directory: "${{ inputs.working-directory }}"
       shell: bash
-      run: $HOME/.luarocks/bin/luacov
+      run: |
+        $HOME/.luarocks/bin/mineunit -r
+        OUT="$(awk -v p=0 '/^----/{p++;next}p==2{exit}p' luacov.report.out)"
+        OUT="${OUT//'%'/'%25'}";OUT="${OUT//$'\n'/'%0A'}"
+        echo "::set-output name=report::${OUT//$'\r'/'%0D'}"
     - name: collect coverage data
       working-directory: "${{ inputs.working-directory }}"
       shell: bash
